#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Build the readsb command line based on options
READSB_BIN="/usr/local/bin/readsb"

READSB_CMD=(--net-only)
READSB_CMD+=(--quiet)

if [ -n "${LAT}" ]; then
    READSB_CMD+=(--lat "${LAT}")
fi

if [ -n "${LONG}" ]; then
    READSB_CMD+=(--lon "${LONG}")
fi

if [ -n "${MLATHOST}" ]; then
    READSB_CMD+=("--net-connector=${MLATHOST},${MLATPORT},beast_in")
fi

READSB_CMD+=("--net-connector=${BEASTHOST},${BEASTPORT},beast_in")

READSB_CMD+=(--write-json=/run/readsb)
READSB_CMD+=(--heatmap-dir /var/globe_history)
READSB_CMD+=(--heatmap 13)
READSB_CMD+=(--json-trace-interval 15)
READSB_CMD+=(--json-reliable 1)
READSB_CMD+=("--max-range=$READSB_MAX_RANGE")

"${READSB_BIN}" "${READSB_CMD[@]}" 2>&1 | awk -W Interactive '{print "[readsb] " $0}'
