#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Build the readsb command line based on options
READSB_BIN="/usr/local/bin/readsb"

READSB_CMD=(--net-only)
READSB_CMD+=(--quiet)

if [ -n "${LAT}" ]; then
    READSB_CMD+=(--lat "${LAT}")
fi

if [ -n "${LONG}" ]; then
    READSB_CMD+=(--lon "${LONG}")
fi

if [ -n "${MLATHOST}" ]; then
    READSB_CMD+=("--net-connector=${MLATHOST},${MLATPORT},beast_in")
fi

if [ -n "${BEASTHOST}" ]; then
    READSB_CMD+=("--net-connector=${BEASTHOST},${BEASTPORT},beast_in")
fi

READSB_CMD+=(--write-json=/run/readsb)
READSB_CMD+=(--heatmap-dir /var/globe_history)
READSB_CMD+=(--heatmap 13)
READSB_CMD+=(--json-trace-interval 15)
READSB_CMD+=(--json-reliable 1)
READSB_CMD+=("--max-range=$READSB_MAX_RANGE")

READSB_CMD+=(--net-ro-port=30002)
READSB_CMD+=(--net-sbs-port=30003)
READSB_CMD+=(--net-bi-port=30004,30104)
READSB_CMD+=(--net-bo-port=30005)
READSB_CMD+=(--forward-mlat)  

# shellcheck disable=SC2086
"${READSB_BIN}" "${READSB_CMD[@]}" $READSB_EXTRA_ARGS 2>&1 | awk -W Interactive '{print "[readsb] " $0}'
