#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if chk_enabled "${GRAPHS1090_DISABLE}"; then
    exec sleep infinity
fi

LOOPTIME="30s"
WRITEAFTER="10"     # restart collectd every $WRITEAFTER loops   

sleep ${LOOPTIME}
counter=0
nice -n 19 s6wrap --prepend=graphs1090 --timestamps --args bash /usr/share/graphs1090/service-graphs1090.sh
if (( counter++ > WRITEAFTER ))
then
    # restart collectd by killing it. This will cause the write-back script to be invoked
    pkill collectd
    counter=0
fi
# sleep ${LOOPTIME}
