#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -n "${GRAPHS1090_DISABLE}" ]]; then
    sleep infinity
fi

LOOPTIME="30s"
WRITEAFTER="10"     # restart collectd every $WRITEAFTER loops   

sleep ${LOOPTIME}
counter=0
nice -n 19 /usr/share/graphs1090/service-graphs1090.sh \
    2>&1 | mawk -W Interactive '{print "[" strftime("%Y-%m-%d %H:%M:%S", systime()) "][graphs1090] " $0}'
if (( counter++ > WRITEAFTER )) 
then
    # restart collectd by killing it. This will cause the write-back script to be invoked
    pkill collectd
    counter=0
fi
# sleep ${LOOPTIME}