#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if [[ "$(ls /etc/nginx/sites-enabled | wc -l)" == "0" ]]; then
    exec sleep infinity
fi


mkdir -p /var/log/nginx

exec s6wrap --quiet --prepend=nginx --timestamps --args /usr/sbin/nginx
