#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if  chk_enabled "${TAR1090_DISABLE}"; then
    exec sleep infinity
fi

mkdir -p /var/log/nginx

exec s6wrap --quiet --prepend=nginx --timestamps --args /usr/sbin/nginx
