#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if [[ "$(find /etc/nginx/sites-enabled/ -type f | wc -l)" == "0" ]]; then
    stop_service
fi


mkdir -p /var/log/nginx

exec s6wrap --quiet --prepend=nginx --timestamps --args /usr/sbin/nginx
