#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2076

source /scripts/common

SDIR=/etc/s6-overlay/startup.d

# exit 0 for nonexistent or empty directory
if ! [[ -d "$SDIR" ]] || [[ -z "$(ls "$SDIR")" ]]; then
    exit 0
fi

for NAME in "$SDIR"/*; do
    if ! s6wrap --quiet --prepend="$NAME" --timestamps --args "$NAME"; then
        s6wrap --quiet --prepend=startup --timestamps --args echo Error running "$NAME"
        exit 1
    fi
done
