#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if chk_enabled "${TAR1090_DISABLE}"; then
    stop_service
fi

mkdir -p /run/tar1090
sleep 5

# shellcheck source=/dev/null
#source "${TAR1090_INSTALL_DIR}/default"

srcdir=/run/readsb
service=readsb

exec s6wrap --quiet --prepend=tar1090 --timestamps --args bash /usr/local/share/tar1090/tar1090.sh \
  "/run/$service" \
  "$srcdir"

  # "$INTERVAL" \
  # "$HISTORY_SIZE" \
  # "$CHUNK_SIZE" \
  # "$ENABLE_978" \
  # "$URL_978" \
  # "$INT_978" \
