#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

trap 'pkill -P $$ || true; exit 0' SIGTERM SIGINT SIGHUP SIGQUIT

# Start telegraf if required
if [[ -n "$INFLUXDBV2_URL" ]] || chk_enabled "${PROMETHEUS_ENABLE}"; then
    if [[ ! -f /usr/bin/telegraf ]]; then
        s6wrap --quiet --prepend=telegraf --timestamps --args echo "WARNING: InfluxDB/Prometheus parameters are set but Telegraf not included in this container"
        exec sleep infinity
    fi
    # give other services time to stabilise
    sleep 5 & wait $!
    # make sure that at least /run/readsb/stats.json is available before we start:
    while [[ ! -f /run/readsb/stats.json ]]; do
        sleep 5 & wait $!
    done
    # start telegraf
    exec s6wrap --quiet --prepend=telegraf --timestamps --args telegraf --config-directory /etc/telegraf/telegraf.d
else
    # if telegraf not needed, sleep forever
    exec sleep infinity
fi
