#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

mkdir -p /var/log/nginx

exec \
  /usr/sbin/nginx 2>&1 | mawk -W interactive '{print "[" strftime("%Y-%m-%d %H:%M:%S", systime()) "][nginx] " $0}'
