#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common
alias s6wrap='s6wrap --quiet'

mkdir -p /var/log/nginx

exec s6wrap --prepend=nginx --timestamps --args /usr/sbin/nginx
