#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if chk_enabled "${GRAPHS1090_DISABLE}"; then
    exit 0
fi

s6wrap --prepend=graphs1090-writeback --timestamps --args bash /usr/share/graphs1090/writeback.sh
