#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ -z "$DISABLE_PERFORMANCE_GRAPHS" ]]; then

    # wait for neccessary input file to exist before starting
    echo "Waiting for readsb to start..." | stdbuf -o0 awk '{print "[collectd] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    while [[ ! -e /usr/share/graphs1090/data-symlink/data/stats.json ]]; do
        sleep 10
    done

    /usr/share/graphs1090/readback.sh
    /usr/sbin/collectd -t -T -f -C /etc/collectd/collectd.conf > /dev/null 2>&1

    set -eo pipefail

    #shellcheck disable=SC2016
    /usr/sbin/collectd \
        -C /etc/collectd/collectd.conf \
        -f \
        2>&1 | grep -v "successfully loaded\." \
        | stdbuf -o0 awk '{print "[collectd] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    /usr/share/graphs1090/writeback.sh
else
    sleep infinity
fi
