#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if chk_enabled "${GRAPHS1090_DISABLE}"; then
    exec sleep infinity
fi


PERMFILE=/var/lib/collectd/rrd/localhost.tar.gz
if chk_enabled "${GRAPHS1090_REDUCE_IO}"; then
    # readback rrd database from compressed archive
    s6wrap --prepend=graphs1090-readback --timestamps --args bash /usr/share/graphs1090/readback.sh
elif [[ -f "${PERMFILE}" ]]; then
    # extract rrd database from compressed archive (in case  WAS enabled)
    if s6wrap --prepend=graphs1090-readback --timestamps --args bash /usr/share/graphs1090/gunzip.sh /var/lib/collectd/rrd/localhost; then
        s6wrap --prepend=graphs1090-readback --timestamps --args rm -v -rf "${PERMFILE}"
    fi
fi


# wait for neccessary input file to exist before starting

# shellcheck disable=SC2016
while [[ ! -e /usr/share/graphs1090/data-symlink/data/stats.json ]]; do
    #if [[ -z "$wait_printed" ]]; then echo "Waiting for readsb to start..."; wait_printed=yes; fi
    sleep 1
done

# test config?
/usr/sbin/collectd -t -T -f -C /etc/collectd/collectd.conf > /dev/null 2>&1


trap "echo 'sending SIGTERM to collectd';pkill collectd" SIGTERM SIGINT SIGHUP SIGQUIT

# background execution + wait is necessary for trap to work -.-
#shellcheck disable=SC2016
s6wrap --prepend=collectd --timestamps --args /usr/sbin/collectd -C /etc/collectd/collectd.conf -f &
wait



if chk_enabled "${GRAPHS1090_REDUCE_IO}"; then
    # writeback
    s6wrap --prepend=graphs1090-writeback --timestamps --args bash /usr/share/graphs1090/writeback.sh
fi


