#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

# Define colours
YELLOW='\033[1;33m'
#LIGHTRED='\033[1;31m'
NOCOLOR='\033[0m'

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${BEASTHOST}" ] && [ -z "${MLATHOST}" ] && [ -z "${READSB_DEVICE_TYPE}" ] && [ -z "${READSB_NET_CONNECTOR}" ]; then
  echo -e "${YELLOW}WARNING: No obvious data input configured: BEASTHOST / MLATHOST / READSB_NET_CONNECTOR / READSB_DEVICE_TYPE environment variables not set${NOCOLOR}"
fi
if [ -z "${LAT}" ] && [ -z "${READSB_LAT}" ]; then
  echo -e "${YELLOW}WARNING: LAT / READSB_LAT environment variable not set, Home location will not be accurate${NOCOLOR}"
fi
if [ -z "${LONG}" ] && [ -z "${READSB_LON}" ]; then
  echo -e "${YELLOW}WARNING: LONG / READSB_LON environment variable not set, Home location will not be accurate${NOCOLOR}"
fi
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -e "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" >/etc/timezone
fi
