#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if chk_enabled "${TAR1090_DISABLE}"; then
    exit 0
fi

# https://github.com/wiedehopf/tar1090#heywhatsthatcom-range-outline

OUT_FILE="${TAR1090_INSTALL_DIR}/html-webroot/upintheair.json"
if [ -n "${HEYWHATSTHAT_PANORAMA_ID}" ]; then

    HEYWHATSTHAT_ALTS="${HEYWHATSTHAT_ALTS:-12192m}"

    if grep -e "[^0-9kmft,]" <<< "${HEYWHATSTHAT_ALTS}" >/dev/null 2>&1; then
        echo "FATAL: Illegal character in HEYWHATSTHAT_ALTS=${HEYWHATSTHAT_ALTS}"
        exit 1
    fi

    # convert all elements to meters
    readarray -td, alts_array <<< "${HEYWHATSTHAT_ALTS:-12192m}"
    for i in "${!alts_array[@]}"
    do
        alts_array[i]="${alts_array[i]//$'\n'/}"
        if [[ ${alts_array[i]: -2} == "km" ]]; then
            alts_array[i]="${alts_array[i]:0:-2}000"
        elif [[ ${alts_array[i]: -1} == "m" ]]; then
            alts_array[i]="${alts_array[i]:0:-1}"
        elif [[ ${alts_array[i]: -2} == "ft" ]]; then
            alts_array[i]="$(bc -l <<< "scale=0; ${alts_array[i]:0:-2}/3.281")"
        else
            alts_array[i]="$(bc -l <<< "scale=0; ${alts_array[i]}/3.281")"
        fi
    done

    # write the results back to $HEYWHATSTHAT_ALTS:
    printf -v HEYWHATSTHAT_ALTS -- "%s," "${alts_array[@]}"
    HEYWHATSTHAT_ALTS="${HEYWHATSTHAT_ALTS:0:-1}"

    HEY_URL="http://www.heywhatsthat.com/api/upintheair.json?id=${HEYWHATSTHAT_PANORAMA_ID}&refraction=0.25&alts=${HEYWHATSTHAT_ALTS:-12192}"

    # in many configurations TAR1090_UPDATE_DIR will persist compose down / up
    mkdir -p "${TAR1090_UPDATE_DIR}"
    URL_FILE="${TAR1090_UPDATE_DIR}/upintheair.json.url"
    PFILE="${TAR1090_UPDATE_DIR}/upintheair.json"

    if [[ -f "${PFILE}" ]] && diff -q "$URL_FILE" <(cat <<<"${HEY_URL}") &>/dev/null; then
        # url identical, use old file
        echo "Using cached HeyWhatsThat Range Outlines for these altitudes (in meters): ${HEYWHATSTHAT_ALTS}"
    else
        echo "Getting HeyWhatsThat Range Outlines for these altitudes (in meters): ${HEYWHATSTHAT_ALTS}"
        if curl --connect-timeout 2 --silent --show-error --output "${PFILE}" "${HEY_URL}"; then
            cat <<<"${HEY_URL}" >"${URL_FILE}"
        else
            echo "WARNING: Unable to download panorama. Outline will not be available."
            # just in case make sure we clear any existing file
            rm -f "${OUT_FILE}"
            exit 0
        fi
    fi

    if [[ -z "$READSB_RX_LOCATION_ACCURACY" ]] || [[ ${READSB_RX_LOCATION_ACCURACY} == 2 ]]; then
        cp -f "${PFILE}" "${OUT_FILE}"
    else
        # best effort: redact location identifying details from heywhatsthat panorama
        # one may still obtain the location with fancy calculations
        jq < "${PFILE}" > "${OUT_FILE}" 'del(.lat) | del(.lon) | del(.id) | del(.elev_amsl)'
    fi
else
    # we need to remove the JSON file if it exists (use case: user removes previously set HEYWHATSTHAT_PANORAMA_ID)
    rm -f "${OUT_FILE}"
fi

exit 0
