#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

if ! chk_enabled "${HTTP_ACCESS_LOG}"; then
    # shellcheck disable=SC1003
    sed -i 's\access_log .*\access_log off;\' /etc/nginx/nginx.conf
else
    # shellcheck disable=SC1003
    sed -i 's\access_log .*\access_log /dev/stdout;\' /etc/nginx/nginx.conf
fi

if ! chk_enabled "${HTTP_ERROR_LOG}"; then
    # shellcheck disable=SC1003
    sed -i 's\error_log .*\error_log /dev/null crit;\' /etc/nginx/nginx.conf
else
    # shellcheck disable=SC1003
    sed -i 's\error_log .*\error_log /dev/stdout notice;\' /etc/nginx/nginx.conf
fi
