#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

mkdir -p /run/graphs1090

# If ${GRAPHS1090_DISABLE} is set, remove access to the graphs1090 website. We don't need to worry about putting this file back
# after graphs1090 is re-enabled, because when changing env params, the container MUST be recreated.
if chk_enabled "${GRAPHS1090_DISABLE}"; then
    mv -f /usr/share/graphs1090/nginx-graphs1090.conf /usr/share/graphs1090/nginx-graphs1090.conf.backup
    touch /usr/share/graphs1090/nginx-graphs1090.conf
    exit 0
fi

# create symlink so /var/cache/fontconfig is in tmpfs
# as per Wiedehopf - https://discord.com/channels/734090820684349521/1102603003376177172/1203826726023729162
# shellcheck disable=SC2174
mkdir -p -m 777 /run/cache/fontconfig
rm -rf /var/cache/fontconfig
ln -sf /run/cache/fontconfig /var/cache/fontconfig

if chk_enabled "${GRAPHS1090_HIDE_SYSTEM}" ; then
    sed -i "s|HIDE_SYSTEM=.*|HIDE_SYSTEM=yes|g" /etc/default/graphs1090
    cp /usr/share/graphs1090/git/hide_system-collectd.conf /etc/collectd/collectd.conf
else
    cp /usr/share/graphs1090/git/collectd.conf /etc/collectd/collectd.conf
fi

if [[ -n "$GRAPHS1090_CPU_TEMP" ]]; then
	# change path for cpu temp
	sed -i -e "s@/sys/class/thermal/thermal_zone0/temp@$GRAPHS1090_CPU_TEMP@" /etc/collectd/collectd.conf
fi

# other temperature
if [[ -n "$GRAPHS1090_OTHER_TEMP1" ]]; then
read -r -d '' _insert <<EOF || true
\n    <Table "$GRAPHS1090_OTHER_TEMP1">\n\
        Instance localhost\n\
        Separator " "\n\
        <Result>\n\
            Type gauge\n\
            InstancePrefix "other_temp1"\n\
            ValuesFrom 0\n\
        </Result>\n\
    </Table>\n
EOF
    sed -i -e 's@<Plugin table>.*@\0'"$_insert"'@' /etc/collectd/collectd.conf
fi

if chk_enabled "${GRAPHS1090_RANGE_INCLUDE_NONADSB}"; then
    sed -i -e 's/range_include_nonadsb = False/range_include_nonadsb = True/' /usr/share/graphs1090/dump1090.py
fi

# ref: https://github.com/wiedehopf/graphs1090/blob/151e63a810d6b087518992d4f366d9776c5c826b/install.sh#L171
sed -i '/<Plugin "interface">/a\ \ \ \ Interface "eth0"' /etc/collectd/collectd.conf
# ref: https://github.com/wiedehopf/graphs1090/blob/151e63a810d6b087518992d4f366d9776c5c826b/install.sh#L218
sed -i -e 's?URL .*?URL "file:///usr/share/graphs1090/data-symlink"?' /etc/collectd/collectd.conf
## Lines below merge the tar1090 collectd config with the graphs1090 collectd config
# remove the default syslog config in collectd.conf
sed -i '/<Plugin\ syslog>/,/<\/Plugin>/d' /etc/collectd/collectd.conf
# replace syslog plugin with logfile plugin in collectd.conf
sed -i 's/LoadPlugin\ syslog/LoadPlugin logfile/' /etc/collectd/collectd.conf
# add configuration to log to STDOUT in collectd.conf ("/a" == append lines after match)
sed -i '/LoadPlugin\ logfile/a\\n<Plugin\ logfile>\n<\/Plugin>' /etc/collectd/collectd.conf
sed -i '/<Plugin\ logfile>/a\ \ \ \ PrintSeverity\ true' /etc/collectd/collectd.conf
sed -i '/<Plugin\ logfile>/a\ \ \ \ Timestamp\ false' /etc/collectd/collectd.conf
sed -i '/<Plugin\ logfile>/a\ \ \ \ File\ STDOUT' /etc/collectd/collectd.conf
sed -i '/<Plugin\ logfile>/a\ \ \ \ LogLevel\ "notice"' /etc/collectd/collectd.conf
# add tar1090 specific stuff
# shellcheck disable=SC2016
sed -i '$a\\n' /etc/collectd/collectd.conf
# shellcheck disable=SC2016
sed -i '$aFQDNLookup\ true' /etc/collectd/collectd.conf

# Disable a few graphs based on parameter settings:
if chk_enabled "${GRAPHS1090_DISABLE_CHART_CPU}"; then
    sed -i '/^\s*<div class="column text-center">$/{$!{N;s/\(<div class="column text-center"\)\(>\n\s*<a id ="system-cpu-link"\)/\1 style="display:none"\2/;t;P;D}}' /usr/share/graphs1090/html/index.html
fi
if chk_enabled "${GRAPHS1090_DISABLE_CHART_TEMP}"; then
    sed -i '/^\s*<div class="column text-center">$/{$!{N;s/\(<div class="column text-center"\)\(>\n\s*<a id ="system-temperature-link"\)/\1 style="display:none"\2/;t;P;D}}' /usr/share/graphs1090/html/index.html
fi
if chk_enabled "${GRAPHS1090_DISABLE_CHART_MEMORY}"; then
    sed -i '/^\s*<div class="column text-center">$/{$!{N;s/\(<div class="column text-center"\)\(>\n\s*<a id ="system-memory-link"\)/\1 style="display:none"\2/;t;P;D}}' /usr/share/graphs1090/html/index.html
fi
if chk_enabled "${GRAPHS1090_DISABLE_CHART_NETWORK_BANDWIDTH}"; then
    sed -i '/^\s*<div class="column text-center">$/{$!{N;s/\(<div class="column text-center"\)\(>\n\s*<a id ="system-network_bandwidth-link"\)/\1 style="display:none"\2/;t;P;D}}' /usr/share/graphs1090/html/index.html
fi
if chk_enabled "${GRAPHS1090_DISABLE_CHART_DISK_USAGE}"; then
    sed -i '/^\s*<div class="column text-center">$/{$!{N;s/\(<div class="column text-center"\)\(>\n\s*<a id ="system-df_root-link"\)/\1 style="display:none"\2/;t;P;D}}' /usr/share/graphs1090/html/index.html
fi
if chk_enabled "${GRAPHS1090_DISABLE_CHART_DISK_IOPS}"; then
    sed -i '/^\s*<div class="column text-center">$/{$!{N;s/\(<div class="column text-center"\)\(>\n\s*<a id ="system-disk_io_iops-link"\)/\1 style="display:none"\2/;t;P;D}}' /usr/share/graphs1090/html/index.html
fi
if chk_enabled "${GRAPHS1090_DISABLE_CHART_DISK_BANDWIDTH}"; then
    sed -i '/^\s*<div class="column text-center">$/{$!{N;s/\(<div class="column text-center"\)\(>\n\s*<a id ="system-disk_io_octets-link"\)/\1 style="display:none"\2/;t;P;D}}' /usr/share/graphs1090/html/index.html
fi

# configure disk preservation
if chk_enabled "${GRAPHS1090_REDUCE_IO}"; then
    sed -i -e 's?DataDir.*?DataDir "/run/collectd"?' /etc/collectd/collectd.conf
    sed -i -e 's#^DB=.*#DB=/run/collectd#' /etc/default/graphs1090
fi

# Enable AIRSPY graphs if requested:
if chk_enabled "${ENABLE_AIRSPY}"; then
    sed -i 's/div id="panel_airspy" class="panel panel-default" style="display:none"/div id="panel_airspy" class="panel panel-default" style="display:block"/g' /usr/share/graphs1090/html/index.html
else
    sed -i 's/div id="panel_airspy" class="panel panel-default" style="display:block"/div id="panel_airspy" class="panel panel-default" style="display:none"/g' /usr/share/graphs1090/html/index.html
fi

# allow for changing the data source for various stats graphs1090 collects
if [[ -n "${URL_AIRSPY}" ]]; then
    sed -i -e "s|^\s*#*\s*URL_AIRSPY.*|            URL_AIRSPY \"${URL_AIRSPY}\"|g" /etc/collectd/collectd.conf
fi

if [[ -n "${URL_1090_SIGNAL}" ]]; then
    sed -i -e "s|^\s*#*\s*URL_1090_SIGNAL.*|            URL_1090_SIGNAL \"${URL_1090_SIGNAL}\"|g" /etc/collectd/collectd.conf
fi

if [[ -n "${URL_1090}" ]]; then
    sed -i -e "s|^\s*URL .*|            URL \"${URL_1090}\"|g" /etc/collectd/collectd.conf
fi

# Enable UAT graphs if URL_978 is set:
if [[ -n "${URL_978}" ]]; then
    sed -i 's/div id="panel_978" class="panel panel-default" style="display:none"/div id="panel_978" class="panel panel-default" style="display:block"/g' /usr/share/graphs1090/html/index.html
    sed -i -e "s|^\s*#*\s*URL_978.*|            URL_978 \"${URL_978}\"|g" /etc/collectd/collectd.conf
else
    sed -i 's/div id="panel_978" class="panel panel-default" style="display:block"/div id="panel_978" class="panel panel-default" style="display:none"/g' /usr/share/graphs1090/html/index.html
    sed -i "s|^\(\s*\)\(URL_978.*$\)|#\1\2|g" /etc/collectd/collectd.conf
fi

# Enable DarkMode if configured:
if chk_enabled "${GRAPHS1090_DARKMODE}"; then
    sed -i 's|colorscheme=default|colorscheme=dark|g' /etc/default/graphs1090
else
    sed -i 's|colorscheme=dark|colorscheme=default|g' /etc/default/graphs1090
fi

#  Set Interval in seconds to feed data into RRD files.
if [[ -n "${GRAPHS1090_RRD_STEP}" ]]; then
    sed -i "s|DRAW_INTERVAL=.*|DRAW_INTERVAL=${GRAPHS1090_RRD_STEP}|g" /etc/default/graphs1090
else
    sed -i "s|DRAW_INTERVAL=.*|DRAW_INTERVAL=60|g" /etc/default/graphs1090
fi

if [[ -n "${GRAPHS1090_RANGEUNITS}" && -z "${GRAPHS1090_RANGE_UNITS}" ]]; then
    GRAPHS1090_RANGE_UNITS="${GRAPHS1090_RANGEUNITS}"
fi
if [[ -z "${GRAPHS1090_RANGE_UNITS}" ]]; then
    GRAPHS1090_RANGE_UNITS="nautical"
fi
# Set range units, possible values: `nautical`, `statute`, `metric`
# shellcheck disable=SC2076
if [[ " nautical statute metric " =~ " ${GRAPHS1090_RANGE_UNITS} " ]]; then
    sed -i "s|^range=.*|range=${GRAPHS1090_RANGE_UNITS}|g" /etc/default/graphs1090
else
    echo "[$(date)][08-graphs1090] WARNING: GRAPHS1090_RANGE_UNITS set to \"${GRAPHS1090_RANGE_UNITS}\", which an invalid value!"
fi

if [[ "${GRAPHS1090_TEMP_UNITS}" == "fahrenheit" ]]; then
    # mind the farenheit misspelling in graphs1090 config, this is not a typo
    sed -i "s|^farenheit=.*|farenheit=1|g" /etc/default/graphs1090
fi

# Set graph size, possible values: `small`, `default`, `large`, `huge`, `custom`
# shellcheck disable=SC2076
if [[ -n "${GRAPHS1090_SIZE}" ]] && [[ " small default large huge custom " =~ " ${GRAPHS1090_SIZE} " ]]; then
    sed -i "s|graph_size=.*|graph_size=${GRAPHS1090_SIZE}|g" /etc/default/graphs1090
elif [[ -n "${GRAPHS1090_SIZE}" ]] && [[ ! " small default large huge custom " =~ " ${GRAPHS1090_SIZE} " ]]; then
    echo "[$(date)][08-graphs1090] WARNING: GRAPHS1090_SIZE set to \"${GRAPHS1090_SIZE}\", which an invalid value!"
else
    sed -i "s|graph_size=.*|graph_size=custom|g" /etc/default/graphs1090
fi

# Make the small graphs as large as the big ones by setting to `yes`
if chk_enabled "${GRAPHS1090_ALL_LARGE}"; then
    sed -i "s|all_large=.*|all_large=yes|g" /etc/default/graphs1090
else
    sed -i "s|all_large=.*|all_large=no|g" /etc/default/graphs1090
fi

# Font size (relative to graph size).
if [[ -n "${GRAPHS1090_FONT_SIZE}" ]]; then
    sed -i "s|font_size=.*|font_size=${GRAPHS1090_FONT_SIZE}|g" /etc/default/graphs1090
else
    sed -i "s|font_size=.*|font_size=10\.0|g" /etc/default/graphs1090
fi

# Set to 1 to draw a reference line at the maximum message rate.
if chk_enabled "${GRAPHS1090_MAX_MESSAGES_LINE}"; then
    sed -i "s|max_message_line=.*|max_message_line=1|g" /etc/default/graphs1090
else
    sed -i "s|max_message_line=.*|max_message_line=0|g" /etc/default/graphs1090
fi

# Defines the width of the larger graphs.
if [[ -n "${GRAPHS1090_LARGE_WIDTH}" ]]; then
    sed -i "s|^lwidth=.*|lwidth=${GRAPHS1090_LARGE_WIDTH}|g" /etc/default/graphs1090
else
    sed -i "s|^lwidth=.*|lwidth=1096|g" /etc/default/graphs1090
fi

# Defines the height of the larger graphs.
if [[ -n "${GRAPHS1090_LARGE_HEIGHT}" ]]; then
    sed -i "s|^lheight=.*|lheight=${GRAPHS1090_LARGE_HEIGHT}|g" /etc/default/graphs1090
else
    sed -i "s|^lheight=.*|lheight=235|g" /etc/default/graphs1090
fi

# Defines the width of the smaller graphs.
if [[ -n "${GRAPHS1090_SMALL_WIDTH}" ]]; then
    sed -i "s|^swidth=.*|swidth=${GRAPHS1090_SMALL_WIDTH}|g" /etc/default/graphs1090
else
    sed -i "s|^swidth=.*|swidth=619|g" /etc/default/graphs1090
fi

# Defines the height of the smaller graphs.
if [[ -n "${GRAPHS1090_SMALL_HEIGHT}" ]]; then
    sed -i "s|^sheight=.*|sheight=${GRAPHS1090_SMALL_HEIGHT}|g" /etc/default/graphs1090
else
    sed -i "s|^sheight=.*|sheight=324|g" /etc/default/graphs1090
fi

# Sets disk device for graphs -- leave empty for default.
if [[ -n "${GRAPHS1090_DISK_DEVICE}" ]]; then
    sed -i "s|disk=.*|disk=${GRAPHS1090_DISK_DEVICE}|g" /etc/default/graphs1090
    # if this disk isn't already in collectd.conf, replace the hda entry with the specified disk
    if ! grep -qs "Disk \"${GRAPHS1090_DISK_DEVICE}\"" /etc/collectd/collectd.conf; then
        sed -i "s|Disk \"hda\"|Disk \"${GRAPHS1090_DISK_DEVICE}\"|g" /etc/collectd/collectd.conf
    fi
fi

# Sets (wired) ethernet device for graphs -- leave empty for default.
if [[ -n "${GRAPHS1090_ETHER_DEVICE}" ]]; then
    sed -i "s|ether=.*|ether=${GRAPHS1090_ETHER_DEVICE}|g" /etc/default/graphs1090
else
    sed -i "s|ether=.*|ether=|g" /etc/default/graphs1090
fi

# Sets wifi device for graphs -- leave empty for default.
if [[ -n "${GRAPHS1090_WIFI_DEVICE}" ]]; then
    sed -i "s|wifi=.*|wifi=${GRAPHS1090_WIFI_DEVICE}|g" /etc/default/graphs1090
else
    sed -i "s|wifi=.*|wifi=|g" /etc/default/graphs1090
fi


if [[ -n "${GRAPHS1090_WWW_TITLE}" ]]; then
    sed -i "s|WWW_TITLE=.*|WWW_TITLE=\"${GRAPHS1090_WWW_TITLE}\"|g" /etc/default/graphs1090
fi
if [[ -n "${GRAPHS1090_WWW_HEADER}" ]]; then
    sed -i "s|WWW_HEADER=.*|WWW_HEADER=\"${GRAPHS1090_WWW_HEADER}\"|g" /etc/default/graphs1090
fi

if [[ -n "$GRAPHS1090_DEFAULT_APPEND" ]]; then
    echo "$GRAPHS1090_DEFAULT_APPEND" >> /etc/default/graphs1090
fi
