#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Determine if we need to start telegraf
START_TELEGRAF=0
if [[ -n "$INFLUXDBV2_URL" ]]; then
    START_TELEGRAF=1
fi
if [[ ${PROMETHEUS_ENABLE^^} == "TRUE" ]]; then
    START_TELEGRAF=1
fi

# Start telegraf if required
if [[ "$START_TELEGRAF" == 1 ]]; then

    # give other services time to stabilise
    sleep 5

    # start telegraf
    telegraf --config-directory /etc/telegraf/telegraf.d 2>&1 | mawk -W interactive '{print "[telegraf] " $0}'

else

    # if telegraf not needed, sleep forever
    sleep infinity
fi
