#!/usr/bin/with-contenv bash
# shellcheck shell=bash

sleep 30

# shellcheck source=/dev/null
source "${TAR1090_INSTALL_DIR}/default"

srcdir=/run/readsb
service=readsb

/usr/local/share/tar1090/tar1090.sh \
  "/run/$service" \
  "$srcdir" \
  2>&1 | awk -W interactive '{print "[tar1090] " $0}'
