#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /run/tar1090
sleep 5

# shellcheck source=/dev/null
#source "${TAR1090_INSTALL_DIR}/default"

srcdir=/run/readsb
service=readsb

/usr/local/share/tar1090/tar1090.sh \
  "/run/$service" \
  "$srcdir" \
  2>&1 | mawk -W interactive '{print "[" strftime("%Y-%m-%d %H:%M:%S", systime()) "][tar1090] " $0}'

  # "$INTERVAL" \
  # "$HISTORY_SIZE" \
  # "$CHUNK_SIZE" \
  # "$ENABLE_978" \
  # "$URL_978" \
  # "$INT_978" \
