#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common
alias s6wrap='s6wrap --quiet'

if chk_enabled "${GRAPHS1090_DISABLE}" || ! chk_enabled "${GRAPHS1090_REDUCE_IO}"; then
    exec sleep infinity
fi

sleep "${GRAPHS1090_REDUCE_IO_FLUSH_IVAL:-1d}"

s6wrap --prepend=graphs1090-writeback --timestamps --args pkill collectd
