#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -n "$ENABLE_TIMELAPSE1090" ]]; then

  # Move timelapse1090 out of /run, and symlink back to /run
  mkdir -p /var/timelapse1090
  ln -s /var/timelapse1090 /run/timelapse1090 || true

  {
    echo "SOURCE=$TIMELAPSE1090_SOURCE"
    echo "INTERVAL=$TIMELAPSE1090_INTERVAL"
    echo "HISTORY=$TIMELAPSE1090_HISTORY"
    echo "CHUNK_SIZE=$TIMELAPSE1090_CHUNK_SIZE"
  } > /etc/default/timelapse1090

  pushd /opt/timelapse1090 >/dev/null || exit 1

  while [[ ! -e /run/readsb/receiver.json ]]; do
    sleep 10
  done

  /opt/timelapse1090/timelapse1090.sh \
    2>&1 | mawk -W interactive '{print "[" strftime("%Y-%m-%d %H:%M:%S", systime()) "][timelapse1090] " $0}'

  popd || exit 1

  sleep 30

else

  sleep infinity

fi
