#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd "${GITPATH_TAR1090_DB}" || exit 1

if [ "${UPDATE_TAR1090}" = "true" ]; then 
	# Attempt to update tar1090 database
	git fetch --depth 1 origin master > /dev/null 2>&1 || exit 0
	git reset --hard origin/master > /dev/null 2>&1 || exit 0
fi

# Print tar1090 database version
DB_VERSION=$(git rev-parse --short HEAD)
echo "tar1090 database version: ${DB_VERSION}"
export DB_VERSION

cd "${GITPATH_TAR1090}" || exit 1

if [ "${UPDATE_TAR1090}" = "true" ]; then 
	# Attempt to update tar1090
	git fetch origin master > /dev/null 2>&1 || exit 0
	git reset --hard origin/master > /dev/null 2>&1 || exit 0

	# get the aircraft db file
	curl \
		--silent \
		--output /aircraft.csv.gz \
		https://raw.githubusercontent.com/wiedehopf/tar1090-db/csv/aircraft.csv.gz  || \
		echo "Failed to download updated aircraft database. Using cached version"

    # copy new aircraft db file in to place
	if [[ -e /aircraft.csv.gz ]]; then
		rm -f "$GITPATH_TAR1090_AC_DB"/aircraft.csv.gz
		mv /aircraft.csv.gz rm "$GITPATH_TAR1090_AC_DB"/aircraft.csv.gz
	fi
fi

# Print tar1090 version
TAR1090_VERSION=$(git rev-parse --short HEAD)
echo "tar1090 version: ${TAR1090_VERSION}"
export TAR1090_VERSION
