#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

# Remove old tar1090
rm -rf "${TAR1090_INSTALL_DIR}" > /dev/null 2>&1 || true

# Recreate directory
mkdir -p "${TAR1090_INSTALL_DIR}"

# Copy files into install directory
cd "${GITPATH_TAR1090}" || exit 1
cp ./nginx.conf "${TAR1090_INSTALL_DIR}"
cp ./install.sh "${TAR1090_INSTALL_DIR}"
cp uninstall.sh "${TAR1090_INSTALL_DIR}"
cp LICENSE "${TAR1090_INSTALL_DIR}"
cp README.md "${TAR1090_INSTALL_DIR}"
cp -R html "${TAR1090_INSTALL_DIR}"
cp tar1090.sh "${TAR1090_INSTALL_DIR}"
cp default "${TAR1090_INSTALL_DIR}"

# Get DB and TAR1090 versions
DB_VERSION=$(git --git-dir="$GITPATH_TAR1090_DB/.git" rev-parse --short HEAD)
# shellcheck disable=SC2034
TAR1090_VERSION="$(git --git-dir="$GITPATH_TAR1090/.git" rev-parse --short HEAD)_$DB_VERSION"

# Copy database
cp -R "${GITPATH_TAR1090_DB}/db" "${TAR1090_INSTALL_DIR}/html"
mv "${TAR1090_INSTALL_DIR}/html/db" "${TAR1090_INSTALL_DIR}/html/db-${DB_VERSION}"
