#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Get DB and TAR1090 versions
DB_VERSION=$(git --git-dir="$GITPATH_TAR1090_DB/.git" rev-parse --short HEAD)
# shellcheck disable=SC2034
TAR1090_VERSION="$(git --git-dir="$GITPATH_TAR1090/.git" rev-parse --short HEAD)_$DB_VERSION"


cd "${TAR1090_INSTALL_DIR}/html" || exit 1
gzip -k -9 dbloader.js
gzip -k -9 defaults.js
gzip -k -9 early.js
gzip -k -9 flags.js
gzip -k -9 formatter.js
gzip -k -9 layers.js
gzip -k -9 markers.js
gzip -k -9 planeObject.js
gzip -k -9 registrations.js
gzip -k -9 script.js
gzip -k -9 colors.css
gzip -k -9 style.css

gzip -k -9 jquery/*.js
gzip -k -9 ol/*.js

gzip -k -9 "db-${DB_VERSION}"/*.js
